# Generated by Django 4.0 on 2021-12-30 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='seller',
        ),
        migrations.AddField(
            model_name='good',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.auction'),
        ),
        migrations.AddField(
            model_name='good',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.counterparty'),
        ),
        migrations.AddField(
            model_name='good',
            name='final_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.lot'),
        ),
        migrations.AddField(
            model_name='good',
            name='starting_price',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='AuctionResults',
        ),
    ]
