# Generated by Django 4.0 on 2021-12-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_remove_good_seller_good_auction_good_buyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='auction',
        ),
    ]
