# Generated by Django 4.0 on 2021-12-30 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_remove_good_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.auction'),
        ),
    ]
