# Generated by Django 4.0 on 2021-12-30 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mountclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mountclub.country'),
        ),
    ]
