# Generated by Django 4.0 on 2021-12-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examine',
            old_name='finish_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='examine',
            name='start_date',
        ),
    ]
