# Generated by Django 4.0 on 2021-12-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_finish_date_examine_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examine',
            name='examination_place',
            field=models.CharField(choices=[('P', "At patient's place"), ('H', 'At hospital')], max_length=100, null=True),
        ),
    ]
